# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TrainingAnalyser.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(830, 747)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 61, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.lineEdit_file_name = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_file_name.setGeometry(QtCore.QRect(80, 10, 421, 21))
        self.lineEdit_file_name.setObjectName(_fromUtf8("lineEdit_file_name"))
        self.label_info_length = QtGui.QLabel(self.centralwidget)
        self.label_info_length.setGeometry(QtCore.QRect(270, 105, 61, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_info_length.setFont(font)
        self.label_info_length.setObjectName(_fromUtf8("label_info_length"))
        self.label_info_date = QtGui.QLabel(self.centralwidget)
        self.label_info_date.setGeometry(QtCore.QRect(10, 105, 71, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_info_date.setFont(font)
        self.label_info_date.setObjectName(_fromUtf8("label_info_date"))
        self.lineEdit_file_newname = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_file_newname.setGeometry(QtCore.QRect(70, 80, 431, 20))
        self.lineEdit_file_newname.setObjectName(_fromUtf8("lineEdit_file_newname"))
        self.lineEdit_file_saveto = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_file_saveto.setGeometry(QtCore.QRect(80, 35, 421, 20))
        self.lineEdit_file_saveto.setObjectName(_fromUtf8("lineEdit_file_saveto"))
        self.label_info_header = QtGui.QLabel(self.centralwidget)
        self.label_info_header.setGeometry(QtCore.QRect(10, 85, 46, 13))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_info_header.setFont(font)
        self.label_info_header.setTextFormat(QtCore.Qt.AutoText)
        self.label_info_header.setScaledContents(False)
        self.label_info_header.setObjectName(_fromUtf8("label_info_header"))
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(749, 200, 71, 40))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 250, 821, 451))
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.webView = QtWebKit.QWebView(self.tab)
        self.webView.setGeometry(QtCore.QRect(0, 0, 821, 431))
        self.webView.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.webView.setObjectName(_fromUtf8("webView"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.label_elevation = QtGui.QLabel(self.tab_4)
        self.label_elevation.setGeometry(QtCore.QRect(-5, 2, 821, 421))
        self.label_elevation.setText(_fromUtf8(""))
        self.label_elevation.setObjectName(_fromUtf8("label_elevation"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.graphicsView = QtGui.QGraphicsView(self.tab_2)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 821, 431))
        self.graphicsView.setAutoFillBackground(False)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.label_speed = QtGui.QLabel(self.tab_2)
        self.label_speed.setGeometry(QtCore.QRect(-1, 4, 811, 406))
        self.label_speed.setText(_fromUtf8(""))
        self.label_speed.setObjectName(_fromUtf8("label_speed"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.label_hr = QtGui.QLabel(self.tab_3)
        self.label_hr.setGeometry(QtCore.QRect(-1, 4, 811, 406))
        self.label_hr.setText(_fromUtf8(""))
        self.label_hr.setObjectName(_fromUtf8("label_hr"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.textEdit_2 = QtGui.QTextEdit(self.tab_5)
        self.textEdit_2.setGeometry(QtCore.QRect(0, 0, 821, 426))
        self.textEdit_2.setObjectName(_fromUtf8("textEdit_2"))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.textEdit_3 = QtGui.QTextEdit(self.tab_6)
        self.textEdit_3.setGeometry(QtCore.QRect(0, 0, 821, 426))
        self.textEdit_3.setObjectName(_fromUtf8("textEdit_3"))
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.pushButton_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 35, 61, 23))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(503, 10, 20, 161))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(520, 10, 310, 160))
        self.label.setStyleSheet(_fromUtf8("image: url(:/bla/image/pRect.png);"))
        self.label.setText(_fromUtf8(""))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 120, 51, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(270, 120, 71, 16))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(270, 135, 81, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 135, 61, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lab_walktime = QtGui.QLabel(self.centralwidget)
        self.lab_walktime.setGeometry(QtCore.QRect(370, 120, 121, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lab_walktime.setFont(font)
        self.lab_walktime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_walktime.setObjectName(_fromUtf8("lab_walktime"))
        self.lab_avgspeed = QtGui.QLabel(self.centralwidget)
        self.lab_avgspeed.setGeometry(QtCore.QRect(370, 135, 121, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lab_avgspeed.setFont(font)
        self.lab_avgspeed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_avgspeed.setObjectName(_fromUtf8("lab_avgspeed"))
        self.lab_climb = QtGui.QLabel(self.centralwidget)
        self.lab_climb.setGeometry(QtCore.QRect(90, 135, 121, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lab_climb.setFont(font)
        self.lab_climb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_climb.setObjectName(_fromUtf8("lab_climb"))
        self.lab_date = QtGui.QLabel(self.centralwidget)
        self.lab_date.setGeometry(QtCore.QRect(80, 105, 131, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lab_date.setFont(font)
        self.lab_date.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_date.setObjectName(_fromUtf8("lab_date"))
        self.lab_tottime = QtGui.QLabel(self.centralwidget)
        self.lab_tottime.setGeometry(QtCore.QRect(80, 120, 131, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lab_tottime.setFont(font)
        self.lab_tottime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_tottime.setObjectName(_fromUtf8("lab_tottime"))
        self.lab_length = QtGui.QLabel(self.centralwidget)
        self.lab_length.setGeometry(QtCore.QRect(360, 105, 131, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lab_length.setFont(font)
        self.lab_length.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_length.setObjectName(_fromUtf8("lab_length"))
        self.comboBox = QtGui.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(80, 160, 121, 22))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 165, 46, 13))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.textEdit = QtGui.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 200, 731, 40))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 185, 61, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 830, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionSave_As = QtGui.QAction(MainWindow)
        self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.pushButton.setText(_translate("MainWindow", "File", None))
        self.label_info_length.setText(_translate("MainWindow", "Length", None))
        self.label_info_date.setText(_translate("MainWindow", "Date", None))
        self.label_info_header.setText(_translate("MainWindow", "File info:", None))
        self.pushButton_2.setText(_translate("MainWindow", "Save", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "WebView", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Elevation", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Speed", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Heartrate", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Stats", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Segments", None))
        self.pushButton_3.setText(_translate("MainWindow", "Save in:", None))
        self.label_2.setText(_translate("MainWindow", "Total time", None))
        self.label_3.setText(_translate("MainWindow", "Walking time", None))
        self.label_4.setText(_translate("MainWindow", "Average speed", None))
        self.label_5.setText(_translate("MainWindow", "Climbing", None))
        self.lab_walktime.setText(_translate("MainWindow", "-", None))
        self.lab_avgspeed.setText(_translate("MainWindow", "-", None))
        self.lab_climb.setText(_translate("MainWindow", "-", None))
        self.lab_date.setText(_translate("MainWindow", "-", None))
        self.lab_tottime.setText(_translate("MainWindow", "-", None))
        self.lab_length.setText(_translate("MainWindow", "-", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "Choose activity", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "Running", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "Walking", None))
        self.comboBox.setItemText(3, _translate("MainWindow", "Cycling", None))
        self.comboBox.setItemText(4, _translate("MainWindow", "Rollerskiing", None))
        self.comboBox.setItemText(5, _translate("MainWindow", "Skiing-X", None))
        self.comboBox.setItemText(6, _translate("MainWindow", "Skiing", None))
        self.label_6.setText(_translate("MainWindow", "Activity", None))
        self.label_7.setText(_translate("MainWindow", "Comments", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionClose.setText(_translate("MainWindow", "Close", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionSave_As.setText(_translate("MainWindow", "Save As", None))

from PyQt4 import QtWebKit

