# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\python_proj\UI-Layout\tunnelProg2.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(790, 584)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 771, 351))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 741, 171))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(220, 50, 101, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(220, 80, 71, 16))
        self.label_5.setObjectName("label_5")
        self.lE_tunnelName = QtWidgets.QLineEdit(self.groupBox)
        self.lE_tunnelName.setGeometry(QtCore.QRect(90, 20, 211, 20))
        self.lE_tunnelName.setObjectName("lE_tunnelName")
        self.lE_profile_from = QtWidgets.QLineEdit(self.groupBox)
        self.lE_profile_from.setGeometry(QtCore.QRect(90, 50, 91, 20))
        self.lE_profile_from.setObjectName("lE_profile_from")
        self.lE_profile_to = QtWidgets.QLineEdit(self.groupBox)
        self.lE_profile_to.setGeometry(QtCore.QRect(90, 80, 91, 20))
        self.lE_profile_to.setObjectName("lE_profile_to")
        self.lE_toDir = QtWidgets.QLineEdit(self.groupBox)
        self.lE_toDir.setGeometry(QtCore.QRect(310, 80, 211, 20))
        self.lE_toDir.setObjectName("lE_toDir")
        self.lE_fromDir = QtWidgets.QLineEdit(self.groupBox)
        self.lE_fromDir.setGeometry(QtCore.QRect(310, 50, 211, 20))
        self.lE_fromDir.setObjectName("lE_fromDir")
        self.lE_inspectedBy = QtWidgets.QLineEdit(self.groupBox)
        self.lE_inspectedBy.setGeometry(QtCore.QRect(90, 110, 211, 20))
        self.lE_inspectedBy.setObjectName("lE_inspectedBy")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 110, 71, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 140, 71, 16))
        self.label_7.setObjectName("label_7")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(310, 140, 41, 23))
        self.pushButton.setObjectName("pushButton")
        self.lE_excelInput = QtWidgets.QLineEdit(self.groupBox)
        self.lE_excelInput.setGeometry(QtCore.QRect(90, 140, 211, 20))
        self.lE_excelInput.setObjectName("lE_excelInput")
        self.pushButton_Help = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Help.setGeometry(QtCore.QRect(360, 140, 31, 23))
        self.pushButton_Help.setObjectName("pushButton_Help")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 200, 741, 71))
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton1 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton1.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.radioButton1.setChecked(True)
        self.radioButton1.setObjectName("radioButton1")
        self.radioButton2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton2.setGeometry(QtCore.QRect(10, 40, 82, 17))
        self.radioButton2.setObjectName("radioButton2")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox.setGeometry(QtCore.QRect(130, 20, 161, 17))
        self.checkBox.setObjectName("checkBox")
        self.pB_createDXF = QtWidgets.QPushButton(self.tab)
        self.pB_createDXF.setGeometry(QtCore.QRect(20, 280, 101, 23))
        self.pB_createDXF.setObjectName("pB_createDXF")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 180, 581, 101))
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 10, 731, 151))
        self.groupBox_4.setObjectName("groupBox_4")
        self.pB_bilag3_excel = QtWidgets.QPushButton(self.groupBox_4)
        self.pB_bilag3_excel.setGeometry(QtCore.QRect(310, 50, 41, 23))
        self.pB_bilag3_excel.setObjectName("pB_bilag3_excel")
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setGeometry(QtCore.QRect(10, 50, 71, 16))
        self.label_12.setObjectName("label_12")
        self.lE_excelInput_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lE_excelInput_2.setGeometry(QtCore.QRect(90, 50, 211, 20))
        self.lE_excelInput_2.setObjectName("lE_excelInput_2")
        self.pB_bilag3_image = QtWidgets.QPushButton(self.groupBox_4)
        self.pB_bilag3_image.setGeometry(QtCore.QRect(310, 80, 41, 23))
        self.pB_bilag3_image.setObjectName("pB_bilag3_image")
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setGeometry(QtCore.QRect(10, 80, 71, 16))
        self.label_13.setObjectName("label_13")
        self.lE_imagefolder_3 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lE_imagefolder_3.setGeometry(QtCore.QRect(90, 80, 211, 20))
        self.lE_imagefolder_3.setObjectName("lE_imagefolder_3")
        self.lE_tunnelName_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lE_tunnelName_2.setGeometry(QtCore.QRect(90, 20, 211, 20))
        self.lE_tunnelName_2.setObjectName("lE_tunnelName_2")
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.label_14.setObjectName("label_14")
        self.pB_bilag3_export = QtWidgets.QPushButton(self.groupBox_4)
        self.pB_bilag3_export.setGeometry(QtCore.QRect(10, 110, 75, 23))
        self.pB_bilag3_export.setObjectName("pB_bilag3_export")
        self.tabWidget.addTab(self.tab_2, "")
        self.Analyze = QtWidgets.QWidget()
        self.Analyze.setObjectName("Analyze")
        self.choose_dxffile = QtWidgets.QPushButton(self.Analyze)
        self.choose_dxffile.setGeometry(QtCore.QRect(340, 10, 41, 23))
        self.choose_dxffile.setObjectName("choose_dxffile")
        self.label_8 = QtWidgets.QLabel(self.Analyze)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 101, 16))
        self.label_8.setObjectName("label_8")
        self.lE_dxf_input = QtWidgets.QLineEdit(self.Analyze)
        self.lE_dxf_input.setGeometry(QtCore.QRect(120, 10, 211, 20))
        self.lE_dxf_input.setObjectName("lE_dxf_input")
        self.pushButton_Help_2 = QtWidgets.QPushButton(self.Analyze)
        self.pushButton_Help_2.setGeometry(QtCore.QRect(390, 10, 31, 23))
        self.pushButton_Help_2.setObjectName("pushButton_Help_2")
        self.label_9 = QtWidgets.QLabel(self.Analyze)
        self.label_9.setGeometry(QtCore.QRect(10, 40, 101, 16))
        self.label_9.setObjectName("label_9")
        self.comboBox = QtWidgets.QComboBox(self.Analyze)
        self.comboBox.setGeometry(QtCore.QRect(120, 40, 211, 22))
        self.comboBox.setCurrentText("")
        self.comboBox.setObjectName("comboBox")
        self.lE_dxf_x = QtWidgets.QLineEdit(self.Analyze)
        self.lE_dxf_x.setGeometry(QtCore.QRect(120, 70, 81, 20))
        self.lE_dxf_x.setObjectName("lE_dxf_x")
        self.label_10 = QtWidgets.QLabel(self.Analyze)
        self.label_10.setGeometry(QtCore.QRect(10, 70, 101, 16))
        self.label_10.setObjectName("label_10")
        self.lE_dxf_y = QtWidgets.QLineEdit(self.Analyze)
        self.lE_dxf_y.setGeometry(QtCore.QRect(230, 70, 81, 20))
        self.lE_dxf_y.setObjectName("lE_dxf_y")
        self.label_11 = QtWidgets.QLabel(self.Analyze)
        self.label_11.setGeometry(QtCore.QRect(210, 70, 21, 16))
        self.label_11.setObjectName("label_11")
        self.pB_analyseDXF = QtWidgets.QPushButton(self.Analyze)
        self.pB_analyseDXF.setGeometry(QtCore.QRect(10, 100, 75, 23))
        self.pB_analyseDXF.setObjectName("pB_analyseDXF")
        self.tabWidget.addTab(self.Analyze, "")
        self.label_info = QtWidgets.QLabel(self.centralwidget)
        self.label_info.setGeometry(QtCore.QRect(20, 370, 47, 13))
        self.label_info.setObjectName("label_info")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 390, 751, 71))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 790, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lE_tunnelName, self.lE_profile_from)
        MainWindow.setTabOrder(self.lE_profile_from, self.lE_profile_to)
        MainWindow.setTabOrder(self.lE_profile_to, self.lE_fromDir)
        MainWindow.setTabOrder(self.lE_fromDir, self.lE_toDir)
        MainWindow.setTabOrder(self.lE_toDir, self.lE_inspectedBy)
        MainWindow.setTabOrder(self.lE_inspectedBy, self.lE_excelInput)
        MainWindow.setTabOrder(self.lE_excelInput, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.radioButton1)
        MainWindow.setTabOrder(self.radioButton1, self.radioButton2)
        MainWindow.setTabOrder(self.radioButton2, self.pB_createDXF)
        MainWindow.setTabOrder(self.pB_createDXF, self.textBrowser)
        MainWindow.setTabOrder(self.textBrowser, self.checkBox)
        MainWindow.setTabOrder(self.checkBox, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.pushButton_Help)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tunnel inspection"))
        self.groupBox.setTitle(_translate("MainWindow", "Add tunnel info"))
        self.label.setText(_translate("MainWindow", "Name: "))
        self.label_2.setText(_translate("MainWindow", "From:"))
        self.label_3.setText(_translate("MainWindow", "To: "))
        self.label_4.setText(_translate("MainWindow", "Direction (down)"))
        self.label_5.setText(_translate("MainWindow", "Direction (up)"))
        self.label_6.setText(_translate("MainWindow", "Inspected by"))
        self.label_7.setText(_translate("MainWindow", "Excel data"))
        self.pushButton.setText(_translate("MainWindow", "...."))
        self.pushButton_Help.setText(_translate("MainWindow", "?"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Choose layout"))
        self.radioButton1.setText(_translate("MainWindow", "Rapport 199"))
        self.radioButton2.setText(_translate("MainWindow", "Region Øst"))
        self.checkBox.setText(_translate("MainWindow", "Uten tegneforklaring"))
        self.pB_createDXF.setText(_translate("MainWindow", "Create DXF"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Create DXF"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Layout"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Bilag_3 Generator"))
        self.pB_bilag3_excel.setText(_translate("MainWindow", "...."))
        self.label_12.setText(_translate("MainWindow", "Excel data"))
        self.pB_bilag3_image.setText(_translate("MainWindow", "...."))
        self.label_13.setText(_translate("MainWindow", "Image folder"))
        self.label_14.setText(_translate("MainWindow", "Tunnel name: "))
        self.pB_bilag3_export.setText(_translate("MainWindow", "Create Bilag 3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Attachment"))
        self.choose_dxffile.setText(_translate("MainWindow", "...."))
        self.label_8.setText(_translate("MainWindow", "DXF file to analyse"))
        self.pushButton_Help_2.setText(_translate("MainWindow", "?"))
        self.label_9.setText(_translate("MainWindow", "Layer to export"))
        self.lE_dxf_x.setText(_translate("MainWindow", "-500"))
        self.label_10.setText(_translate("MainWindow", "Max / Min"))
        self.lE_dxf_y.setText(_translate("MainWindow", "500"))
        self.label_11.setText(_translate("MainWindow", "/"))
        self.pB_analyseDXF.setText(_translate("MainWindow", "Analyze"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Analyze), _translate("MainWindow", "Analyze"))
        self.label_info.setText(_translate("MainWindow", "Info:"))

